import { getFooter } from '../../lib/menuHelper.js';

// Advanced Unicode symbols (NOT emojis):
// ◈ = White diamond containing black small diamond (header decorator)
// ◇ = White diamond
// ➥ = Rightwards arrow (command bullet)
// □ = White square (section terminator)
// ┃ = Box drawings light vertical (left spine)
// ⟡ = White diamond minus black x (alt diamond)
// ⬡ = White hexagon (category icon)
// ⬢ = Black hexagon (filled category icon)
// ✦ = Black four pointed star
// ❖ = Black diamond minus white x
// ⚡ = High voltage sign (only for KLAUS brand, not an emoji in all renderers)
// ⚙ = Gear
// ☰ = Trigram for heaven (menu/list icon)
// ⟐ = Right white circle with upper right quadrant (download icon)
// ⚕ = Staff of aesculapius (info/health icon)
// ⚠ = Warning sign
// ♔ = White chess king (owner/crown)
// ⬟ = Black pentagon (tools icon)

export const getBoxStyleCommands = () => {
  return [
    `◈ ◇ KLAUS MD ◇`,
    ``,
    `◈ ❖ ADMIN MENU ❖`,
    `➥ .add`,
    `➥ .promote`,
    `➥ .demote`,
    `➥ .kick`,
    `➥ .ban`,
    `➥ .unban`,
    `➥ .mute`,
    `➥ .unmute`,
    `➥ .warn`,
    `➥ .setname`,
    `➥ .setdesc`,
    `➥ .revoke`,
    `➥ .tagall`,
    `➥ .hidetag`,
    `➥ .link`,
    `➥ .leave`,
    `□`,
    ``,
    `◈ ❖ ANTI MENU ❖`,
    `➥ .antilink`,
    `➥ .antibot`,
    `➥ .anticall`,
    `➥ .antidelete`,
    `➥ .antisticker`,
    `➥ .antiimage`,
    `➥ .antivideo`,
    `➥ .antiaudio`,
    `□`,
    ``,
    `◈ ❖ AI MENU ❖`,
    `➥ .chatgpt`,
    `➥ .gemini`,
    `➥ .claudeai`,
    `➥ .deepseek`,
    `➥ .copilot`,
    `➥ .blackbox`,
    `➥ .bing`,
    `➥ .bard`,
    `➥ .cohere`,
    `➥ .falcon`,
    `➥ .dolphin`,
    `□`,
    ``,
    `◈ ❖ MEDIA MENU ❖`,
    `➥ .song`,
    `➥ .play`,
    `➥ .ytmusic`,
    `➥ .ytv`,
    `➥ .ytmp4`,
    `➥ .tts`,
    `➥ .tovoice`,
    `➥ .tovideo`,
    `➥ .tosticker`,
    `➥ .toimage`,
    `➥ .vv`,
    `➥ .status`,
    `➥ .groupst`,
    `➥ .logo`,
    `□`,
    ``,
    `◈ ❖ DOWNLOAD MENU ❖`,
    `➥ .facebook`,
    `➥ .instagram`,
    `➥ .twitter`,
    `➥ .snapchat`,
    `➥ .mediafire`,
    `➥ .apk`,
    `➥ .playlist`,
    `□`,
    ``,
    `◈ ❖ DESIGN MENU ❖`,
    `➥ .neonlogo`,
    `➥ .firelogo`,
    `➥ .goldlogo`,
    `➥ .silverlogo`,
    `➥ .rainbowlogo`,
    `➥ .dragonlogo`,
    `➥ .phoenixlogo`,
    `➥ .moonlogo`,
    `➥ .lightninglogo`,
    `➥ .crystallogo`,
    `□`,
    ``,
    `◈ ❖ TOOLS MENU ❖`,
    `➥ .ping`,
    `➥ .uptime`,
    `➥ .speed`,
    `➥ .translate`,
    `➥ .wiki`,
    `➥ .define`,
    `➥ .weather`,
    `➥ .calc`,
    `➥ .qr`,
    `➥ .url`,
    `➥ .shorturl`,
    `➥ .google`,
    `➥ .remind`,
    `➥ .iplookup`,
    `□`,
    ``,
    `◈ ❖ FUN MENU ❖`,
    `➥ .truth`,
    `➥ .dare`,
    `➥ .joke`,
    `➥ .quote`,
    `➥ .fact`,
    `➥ .dice`,
    `➥ .8ball`,
    `➥ .coinflip`,
    `➥ .slots`,
    `➥ .trivia`,
    `➥ .wordle`,
    `➥ .chess`,
    `□`,
    ``,
    `◈ ❖ MUSIC MENU ❖`,
    `➥ .lyrics`,
    `➥ .shazam`,
    `➥ .spotify`,
    `➥ .musicmenu`,
    `□`,
    ``,
    `◈ ❖ GAMES MENU ❖`,
    `➥ .chess`,
    `➥ .wordle`,
    `➥ .trivia`,
    `➥ .slots`,
    `➥ .hangman`,
    `➥ .snake`,
    `➥ .numberguess`,
    `➥ .memory`,
    `➥ .ttt`,
    `□`,
    ``,
    `◈ ❖ INFO MENU ❖`,
    `➥ .owner`,
    `➥ .about`,
    `➥ .repo`,
    `➥ .whoami`,
    `➥ .sessioninfo`,
    `➥ .sessionid`,
    `➥ .platform`,
    `➥ .prefixinfo`,
    `➥ .uptime`,
    `□`,
    ``,
    `◈ ❖ OWNER MENU ❖`,
    `➥ .setbotname`,
    `➥ .setprefix`,
    `➥ .setmode`,
    `➥ .settimezone`,
    `➥ .restart`,
    `➥ .shutdown`,
    `➥ .broadcast`,
    `➥ .sessionid`,
    `➥ .pair`,
    `□`,
    ``,
    `◈ ♔ OWNER : KLAUS TECH`,
    `➥ +254711815459`,
    `◈ ◇ POWERED BY KLAUS LABS ◇`,
  ].join('\n');
};
