import { getFooter } from '../../lib/menuHelper.js';

export const getBoxStyleCommands = () => {
  return [
    `┃◈ ⚡ KLAUS MD BOT ◈`,
    ``,
    `┃◈ 🛡️ ADMIN MENU ◈`,
    `┃➥ .add`,
    `┃➥ .promote`,
    `┃➥ .demote`,
    `┃➥ .kick`,
    `┃➥ .ban`,
    `┃➥ .unban`,
    `┃➥ .mute`,
    `┃➥ .unmute`,
    `┃➥ .warn`,
    `┃➥ .setname`,
    `┃➥ .setdesc`,
    `┃➥ .revoke`,
    `┃➥ .tagall`,
    `┃➥ .hidetag`,
    `┃➥ .link`,
    `┃➥ .leave`,
    `┃□`,
    ``,
    `┃◈ 🚫 ANTI MENU ◈`,
    `┃➥ .antilink`,
    `┃➥ .antibot`,
    `┃➥ .anticall`,
    `┃➥ .antidelete`,
    `┃➥ .antisticker`,
    `┃➥ .antiimage`,
    `┃➥ .antivideo`,
    `┃➥ .antiaudio`,
    `┃□`,
    ``,
    `┃◈ 🤖 AI MENU ◈`,
    `┃➥ .chatgpt`,
    `┃➥ .gemini`,
    `┃➥ .claudeai`,
    `┃➥ .deepseek`,
    `┃➥ .copilot`,
    `┃➥ .blackbox`,
    `┃➥ .bing`,
    `┃➥ .bard`,
    `┃➥ .cohere`,
    `┃➥ .falcon`,
    `┃➥ .dolphin`,
    `┃□`,
    ``,
    `┃◈ 🎬 MEDIA MENU ◈`,
    `┃➥ .song`,
    `┃➥ .play`,
    `┃➥ .ytmusic`,
    `┃➥ .ytv`,
    `┃➥ .ytmp4`,
    `┃➥ .tts`,
    `┃➥ .tovoice`,
    `┃➥ .tovideo`,
    `┃➥ .tosticker`,
    `┃➥ .toimage`,
    `┃➥ .vv`,
    `┃➥ .status`,
    `┃➥ .groupst`,
    `┃➥ .logo`,
    `┃□`,
    ``,
    `┃◈ 📥 DOWNLOAD MENU ◈`,
    `┃➥ .facebook`,
    `┃➥ .instagram`,
    `┃➥ .twitter`,
    `┃➥ .snapchat`,
    `┃➥ .mediafire`,
    `┃➥ .apk`,
    `┃➥ .playlist`,
    `┃□`,
    ``,
    `┃◈ 🎨 DESIGN MENU ◈`,
    `┃➥ .neonlogo`,
    `┃➥ .firelogo`,
    `┃➥ .goldlogo`,
    `┃➥ .silverlogo`,
    `┃➥ .rainbowlogo`,
    `┃➥ .dragonlogo`,
    `┃➥ .phoenixlogo`,
    `┃➥ .moonlogo`,
    `┃➥ .lightninglogo`,
    `┃➥ .crystallogo`,
    `┃□`,
    ``,
    `┃◈ 🔧 TOOLS MENU ◈`,
    `┃➥ .ping`,
    `┃➥ .uptime`,
    `┃➥ .speed`,
    `┃➥ .translate`,
    `┃➥ .wiki`,
    `┃➥ .define`,
    `┃➥ .weather`,
    `┃➥ .calc`,
    `┃➥ .qr`,
    `┃➥ .url`,
    `┃➥ .shorturl`,
    `┃➥ .google`,
    `┃➥ .remind`,
    `┃➥ .iplookup`,
    `┃□`,
    ``,
    `┃◈ 🎮 FUN MENU ◈`,
    `┃➥ .truth`,
    `┃➥ .dare`,
    `┃➥ .joke`,
    `┃➥ .quote`,
    `┃➥ .fact`,
    `┃➥ .dice`,
    `┃➥ .8ball`,
    `┃➥ .coinflip`,
    `┃➥ .slots`,
    `┃➥ .trivia`,
    `┃➥ .wordle`,
    `┃➥ .chess`,
    `┃□`,
    ``,
    `┃◈ 🎵 MUSIC MENU ◈`,
    `┃➥ .lyrics`,
    `┃➥ .shazam`,
    `┃➥ .spotify`,
    `┃➥ .musicmenu`,
    `┃□`,
    ``,
    `┃◈ 🎮 GAMES MENU ◈`,
    `┃➥ .chess`,
    `┃➥ .wordle`,
    `┃➥ .trivia`,
    `┃➥ .slots`,
    `┃➥ .hangman`,
    `┃➥ .snake`,
    `┃➥ .numberguess`,
    `┃➥ .memory`,
    `┃➥ .ttt`,
    `┃□`,
    ``,
    `┃◈ ℹ️ INFO MENU ◈`,
    `┃➥ .owner`,
    `┃➥ .about`,
    `┃➥ .repo`,
    `┃➥ .whoami`,
    `┃➥ .sessioninfo`,
    `┃➥ .sessionid`,
    `┃➥ .platform`,
    `┃➥ .prefixinfo`,
    `┃➥ .uptime`,
    `┃□`,
    ``,
    `┃◈ 👑 OWNER MENU ◈`,
    `┃➥ .setbotname`,
    `┃➥ .setprefix`,
    `┃➥ .setmode`,
    `┃➥ .settimezone`,
    `┃➥ .restart`,
    `┃➥ .shutdown`,
    `┃➥ .broadcast`,
    `┃➥ .sessionid`,
    `┃➥ .pair`,
    `┃□`,
    ``,
    `┃◈ *👑 OWNER: KLAUS TECH*`,
    `┃➥ +254711815459`,
    `┃◈ *⚡ POWERED BY KLAUS LABS*`,
  ].join('\n');
};
